name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Create google-services.json
        run: |
          python3 - <<'PY'
          import os, base64
          data = base64.b64decode(os.environ['GOOGLE_SERVICES_JSON'])
          with open('android/app/google-services.json', 'wb') as f:
              f.write(data)
          PY

      - run: flutter build apk --release

      - run: npm install -g firebase-tools

      - run: |
          firebase appdistribution:distribute \
          build/app/outputs/flutter-apk/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --groups testers \
          --token ${{ secrets.FIREBASE_TOKEN }}