name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: flutter build apk --release

      - run: npm install -g firebase-tools

      - run: |
          firebase appdistribution:distribute \
          build/app/outputs/flutter-apk/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --groups testers \
          --token ${{ secrets.FIREBASE_TOKEN }}